version: '3.7'

services:
  postgres:
      image: postgres
      ports: 
        - "5432:5432"
      environment:
        POSTGRES_PASSWORD: mysecretpassword
  elk:
      image: sebp/elk
      ports:
        - "5601:5601"
        - "9200:9200"
        - "5044:5044"
